Dynamically fetch websocket subscription url
Danielhiversen/pyTibber pull request #213
Opened 2022-10-28 13:51 UTC by toini

2022-11-07 19:28 UTC, leetal commented
This is of utter importance at the moment since Tibber decided to enable the new WSS enpoints ahead of its planned December launch 🤦‍♂️The Home Assistant integration (+ any more that relies on this library) will be unavailable unless manually edited.

2022-11-08 09:02 UTC, toini commented
@leetal the new websocket server is available for testing. Note that there was an unrelated outage in api.tibber.com (affecting websockets) yesterday between 13 - 21 CET.

2023-01-04 07:49 UTC, toini commented on tibber/__init__.py
> +            if subs[0].get("status", "ended") is not None and subs[0].get("status", "ended").lower() == "running":
This is not related to fetching websocket url but i was getting errors when testing on a home with no subs

2023-01-05 07:21 UTC, Danielhiversen requested changes

2023-01-05 07:21 UTC, Danielhiversen commented on tibber/__init__.py
> +                and subs[0].get("status", "ended").lower() == "running"
```suggestion
                subs[0].get("status") is not None
                and subs[0]["status"].lower() == "running"
```

2023-01-05 07:21 UTC, Danielhiversen commented on tibber/__init__.py
> +        self.sub_manager: Client = None  # type: ignore
```suggestion
        self.sub_manager: Client | None = None
```

2023-01-05 12:38 UTC, toini commented on tibber/__init__.py
> +        self.sub_manager: Client = None  # type: ignore
I think this made mypy fail now

2023-01-05 12:39 UTC, toini commented on tibber/__init__.py
> +        self.sub_manager: Client = None  # type: ignore
Did this appear after the change?

```Run mypy --disallow-incomplete-defs --no-implicit-optional $SRC_FOLDER
tibber/__init__.py:82: error: Item "None" of "Optional[Client]" has no attribute "close_async"  [union-attr]
tibber/__init__.py:89: error: Argument 1 to "TibberWebsocketsTransport" has incompatible type "None"; expected "str"  [arg-type]
tibber/__init__.py:281: error: Item "None" of "Optional[Client]" has no attribute "transport"  [union-attr]
tibber/__init__.py:282: error: Item "None" of "Optional[Client]" has no attribute "transport"  [union-attr]
Found 4 errors in 1 file (checked 4 source files)
Error: Process completed with exit code 1.
```

2023-01-09 20:50 UTC, Danielhiversen commented on tibber/__init__.py
> +        self.sub_manager: Client = None  # type: ignore
With your changes self.sub_manager can now be None.
So you need to test if self.sub_manager is None before using it.
For example In [rt_disconnect](https://github.com/Danielhiversen/pyTibber/blob/0.26.7/tibber/__init__.py#L82)

2023-01-14 06:36 UTC, merged

2023-01-19 11:43 UTC, p4fg commented
Any progress on this? Waiting with anticipation!

2023-01-20 11:53 UTC, toini commented
@p4fg you can clone the latest code. It works.

2023-01-20 12:04 UTC, p4fg commented
Yeah, im using it via pip3 in a build-pipeline... so i'll see what i can do.

2023-01-27 17:05 UTC, Danielhiversen commented
[0.27.0 ](https://github.com/Danielhiversen/pyTibber/releases/tag/0.27.0) is now released.

Home Assistant would also need to be updated to use the latest library and the new endpoint.

2023-01-30 10:39 UTC, toini commented
@Danielhiversen like this? https://github.com/tibber/core/commit/5cb70ced1ad72c389e45b69ce3037fc885064535